# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rwkapp', '0002_auto_20180316_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='rwk_eintrag',
            name='ringe',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rwk_eintrag',
            name='rwk_mannschaft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rwkapp.RWK_Mannschaft'),
        ),
    ]
