# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rwkapp', '0003_auto_20180316_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rwk_eintrag',
            name='rwk_mannschaft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rwkapp.RWK_Mannschaft'),
        ),
    ]
