# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rwkapp', '0004_auto_20180316_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rwk_eintrag',
            old_name='anzahl_0',
            new_name='anzahl_0er',
        ),
        migrations.RenameField(
            model_name='rwk_eintrag',
            old_name='anzahl_1',
            new_name='anzahl_1er',
        ),
        migrations.RenameField(
            model_name='rwk_eintrag',
            old_name='anzahl_2',
            new_name='anzahl_2er',
        ),
        migrations.RenameField(
            model_name='rwk_eintrag',
            old_name='anzahl_3',
            new_name='anzahl_3er',
        ),
        migrations.RenameField(
            model_name='rwk_eintrag',
            old_name='anzahl_4',
            new_name='anzahl_4er',
        ),
        migrations.RenameField(
            model_name='rwk_eintrag',
            old_name='anzahl_5',
            new_name='anzahl_5er',
        ),
        migrations.RenameField(
            model_name='rwk_eintrag',
            old_name='anzahl_6',
            new_name='anzahl_6er',
        ),
        migrations.RenameField(
            model_name='rwk_eintrag',
            old_name='anzahl_7',
            new_name='anzahl_7er',
        ),
        migrations.RenameField(
            model_name='rwk_eintrag',
            old_name='anzahl_8',
            new_name='anzahl_8er',
        ),
        migrations.AlterField(
            model_name='rwk_eintrag',
            name='rwk_mannschaft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rwkapp.RWK_Mannschaft'),
        ),
    ]
