# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rwkapp', '0005_auto_20180320_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='RWK_Einzahlung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betrag', models.FloatField(default=0)),
                ('tag_der_einzahlung', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rwk_schuetze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rwkapp.RWK_Schuetze')),
            ],
        ),
        migrations.AlterField(
            model_name='rwk_eintrag',
            name='ringe',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rwk_eintrag',
            name='rwk_mannschaft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rwkapp.RWK_Mannschaft'),
        ),
    ]
