# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rwkapp', '0006_auto_20180321_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='rwk_eintrag',
            name='created_by',
            field=models.CharField(default='not_set', max_length=200),
        ),
        migrations.AddField(
            model_name='rwk_einzahlung',
            name='created_by',
            field=models.CharField(default='not_set', max_length=200),
        ),
        migrations.AlterField(
            model_name='rwk_eintrag',
            name='rwk_mannschaft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rwkapp.RWK_Mannschaft'),
        ),
    ]
